FROM alpine:latest
RUN apk update  
RUN apk add python3 py3-pip 
RUN pip install generss --break-system-packages
# copy crontabs for root user
COPY config/cronjobs /etc/crontabs/root

# start crond with log level 8 in foreground, output to stderr
CMD ["crond", "-f", "-d", "8"]
